variables:
  OBJECTS_DIRECTORY: "obj"
  NUGET_PACKAGES_DIRECTORY: ".nuget"
  SOURCE_CODE_PATH: "src/GrillBot"

stages:
  - Build
  - Unit tests

cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - "$SOURCE_CODE_PATH/$OBJECTS_DIRECTORY/project.assets.json"
    - "$SOURCE_CODE_PATH/$OBJECTS_DIRECTORY/*.csproj.nuget.*"
    - "$NUGET_PACKAGES_DIRECTORY"

  policy: pull-push

build:
  image: mcr.microsoft.com/dotnet/sdk:6.0
  stage: Build
  script:
    - "dotnet restore $SOURCE_CODE_PATH --packages $NUGET_PACKAGES_DIRECTORY"
    - "dotnet build $SOURCE_CODE_PATH --no-restore -c Release"

tests:
  image: mcr.microsoft.com/dotnet/sdk:6.0
  stage: Unit tests
  script:
    - "apt-get update"
    - "echo 'msttcorefonts msttcorefonts/accepted-mscorefonts-eula select true' | debconf-set-selections"
    - "apt-get install -y --allow-unauthenticated ttf-mscorefonts-installer* fontconfig"
    - "fc-cache -fv"
    - "dotnet restore $SOURCE_CODE_PATH --packages $NUGET_PACKAGES_DIRECTORY"
    - 'dotnet test $SOURCE_CODE_PATH --no-restore --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"'
  artifacts:
    when: always
    paths:
      - ./**/*test-result.xml
    reports:
      junit:
        - ./**/*test-result.xml
