name: Check content (json, md, ...)

on:
  push:
    branches: [ master ]
    paths:
    - '**.json'
    - '**.md'
    - '.github/workflows/content.yml'
  pull_request:
    types: [ opened, reopened, synchronize ]
    paths:
    - '**.json'
    - '**.md'
    - '.github/workflows/content.yml'

jobs:
  CheckMarkdownFiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: markdownlint
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
          args: "./README.md CONTRIBUTING.md SECURITY.md"

  CheckJsonFiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: JSON syntax check
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/json-lint/master/pipeline.sh)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Crosscheck JSON content
        run: python3 src/CI/check-texts.py


