name: Build and deploy to container registry

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ master ]

jobs:
  CheckStaticContent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Markdown lint
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
          args: "README.md CONTRIBUTING.md SECURITY.md"
      - name: Check json content
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/json-lint/master/pipeline.sh)
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Crosscheck JSON content
        run: python3 CI/check-texts.py
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Try build container
        shell: bash
        working-directory: src
        run: |
          sudo docker build -t grillbot-test-image -f ./Dockerfile .
          sudo docker rmi $(docker images --format "{{.Repository}}:{{.Tag}}" | grep 'grillbot-test-image')
  Deployment:
    runs-on: ubuntu-latest
    needs: Build
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: src/
          push: true
          tags: ghcr.io/grillbot/grillbot:latest
