name: Project build and tests

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'src/GrillBot.Data/Resources/Localization/*.json'
    - '**.md'
  pull_request:
    types: [ opened, reopened, synchronize ]
    paths-ignore:
    - 'src/GrillBot.Data/Resources/Localization/*.json'
    - '**.md'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run build of testing image
        shell: bash
        working-directory: src/GrillBot
        run: |
          sudo docker build -t grillbot-test-image -f ./Dockerfile.Test .
          sudo docker rmi $(docker images --format "{{.Repository}}:{{.Tag}}" | grep 'grillbot-test-image')
